### ISSUE TITLE
How do you want us to submit new artwork into the repo?

### ISSUE THREAD

**Issue by BethMassi** [dotnet/swag#2]
@martinwoodward it looks like we would submit a PR to add a folder with our artwork and update the readme with a png image from the folder? Are there requirements on what formats we should make sure we submit?

**Comment by martinwoodward** [comment]
Let's keep things lightweight for now and we can put more in place if we get lots of assets.  For now thinking:

1. Create a unique folder at the root of the repo for the graphic
1. Upload images into folder. Should have the source image in whatever format it was created along with at least PDF if vector, Hi-res PNG, Small PNG (for previews). Also include EPS and SVG versions of vector images if you have them.
1. Add a section in the ReadMe to show the graphic

See PR #3 as an example.

Make sense?

**Comment by BethMassi** [comment]
:+1:
