### ISSUE TITLE
DotNetSource logo link to GitHub should be https

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/swag#7]
The [DotNetSource](https://github.com/dotnet/swag/blob/master/dotnet_source/DotNetSource_hi.png) logo in this repo and on [stickermule](https://www.stickermule.com/marketplace/5901-dot-net-source-code) has a link to the dotnet GitHub repos, but unfortunately it is http. Would be great to update this to https to keep everyone safe :lock: :lipstick:

**Comment by richlander** [comment]
/cc @martinwoodward 

I agree. This does appear to be a rookie mistake.

**Comment by martinwoodward** [comment]
Thanks. @kuhlenh, if you get chance to spin up AI feel free to fix this one - otherwise I'll take a look in the morning.

**Comment by martinwoodward** [comment]
Actually, I'm on this now but I'll need @kuhlenh or someone else to update the EPS version if that's ok
